### ISSUE TITLE
Replace or cooperate？

### ISSUE THREAD

**Issue by Beanmar** [Boyiliee/PONO#1]
Hi teacher,I want to use PN in my project now,but I have a question,should I replace PN with BN or let BN and PN work together? Which one will get a better result? Thank you !

**Comment by felixgwu** [comment]
Hi @Beanmar,

Thank you for your interest. Based on our ablation study on image-to-image translation, using PONO and BN together leads to better results. However, we cannot guarantee it on other tasks. We are working on exploring PONO on other tasks.

Best,
Felix

**Comment by Boyiliee** [comment]
Hi, @Beanmar ,

Thanks for your interest in PONO.

Based on our research on generative models with PONO and Moment Shortcut, we find they could be compatible with BN and would help improve the performance if used appropriately.

Since I am not sure what kind of project you are doing now, my suggestion is that you could try both and find the best way to use it.  [ I would feel very glad if it could help your project. ;) ]

Hope this helps. 

Boyi

**Comment by felixgwu** [comment]
I am closing this issue. Please feel free to re-open it if you have other questions.

**Comment by Beanmar** [comment]
OK, thank you  teachers!
